version: '3.4'

services:
  ubuntu16:
    build:
      context: .
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: xenial
    command: make depsdev build_in_docker
