version: '3.4'

services:
  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos7
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: el7
    command: make depsdev build_in_docker build_static_in_docker build_rpm
  centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos6
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: el6
    command: make depsdev build_in_docker build_static_in_docker build_rpm
  ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu16
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: xenial
    command: make depsdev build_in_docker build_static_in_docker build_deb
